### ISSUE TITLE
Doesn't load data packs for servers

### ISSUE THREAD

**Issue by paperclone22** [Commander07/data-loader#1]
disclaimer, I've been able to use this mod just fine for single player worlds.

data-loader isn't loading data packs when used in a server setting.

I used the file data-loader-1.0.0.jar from the modrinth link https://modrinth.com/mod/dataloader/version/RWYHtoRI .

The bug can be replicated by setting up a fabric 1.18.1 server either on the local dev machine or a hosted server with data-loader in the mods folder.

**Comment by Commander07** [comment]
This has been fixed in version 1.1.2 which can be found [here](https://modrinth.com/mod/dataloader/version/1.1.2+1.19.4).
