### ISSUE TITLE
Fix or document Quilt incompatibility

### ISSUE THREAD

**Issue by dhouck** [Commander07/data-loader#12]
This mod does not work on Quilt with the standard QFAPI; it crashes when trying to enter a world or load the Create New World screen; see https://mclo.gs/3emFHB8.  Iʼm not sure I quite follow the reasons why, but someone on the Quilt server suggested that if you changed https://github.com/Commander07/data-loader/blob/master/src/main/java/dataloader/mixin/MinecraftServerMixin.java#L18 to inject at `TAIL` instead of `HEAD` it should work.  They also said itʼd be recommended to use the [Resource Loader API](https://maven.fabricmc.net/docs/fabric-api-0.91.6+1.20.2/net/fabricmc/fabric/api/resource/package-summary.html) instead of using that directly.

I have not yet tried to build and test this change myself, which is why Iʼm not making a PR.

**Comment by Commander07** [comment]
This has been fixed in version [1.1.5](https://modrinth.com/mod/dataloader/version/1.1.5+1.20.2-1.20.4).
