### ISSUE TITLE
Crash with 1.20.5-rc2

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#14]
Well, just for curiosity and tried to place Data Loader in a test 1.20.5-rc2 profile (with only Fabric API) to see if it would boot (like it did with 1.20.3 and 1.20.4). Unfortunately not. I think a mixin error.

For the sake of information (and maybe help showing what parts need to be changed for a 1.20.5 port), here's the crash log:
https://gist.github.com/vico93/2cd43eea6e6192751b52502bd5c7eb93

**Comment by vico93** [comment]
Any update? @Commander07

**Comment by Commander07** [comment]
I have updated it to support both 1.20.5 and 1.20.6 it should be available on GitHub, Modrinth and Curseforge soon.

**Comment by vico93** [comment]
Thank you so much!
