### ISSUE TITLE
Adding mod internal datapacks into the loadOrder array

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#15]
Basically, i'm using [Custom Piglin Bartering](https://modrinth.com/mod/custom-piglin-bartering) to fix some stuff about piglins, it cames with two internal datapacks: `default_custom_piglin_barters` and `vanilla_piglin_barters`.

I tried to put them in the `loadOrder` field in `data-loader.json` with either colon or slashes separating the mod id (eg.: `"custom_piglin_bartening:vanilla_piglin_barters"` or `"custom_piglin_bartening/vanilla_piglin_barters"`) and the datapack name, but in both cases the datapacks weren't preadded to the activated datapack list in singleplayer.

What i'm doing wrong - or data loader is even able to fetch mod internal datapacks like it does with vanilla ones?

**Comment by Commander07** [comment]
You have misspelled the id for the mod, it is `custom_piglin_bartering` not `custom_piglin_bartening`. Data loader should be able to load them once specified in `loadOrder`.

**Working config to load both internal packs:**
```json
{
    "onlyLoadSpecified": false,
    "loadOrder": [
        "custom_piglin_bartering:default_custom_piglin_barters",
        "custom_piglin_bartering:vanilla_piglin_barters"
    ]
}
```

**Comment by vico93** [comment]
I'm a moron. Sorry for that!
