### ISSUE TITLE
Update to 1.19+ plus one tweak

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#2]
I'm really interested in this mod. It's annoying that Mojang didn't consider this concept on vanilla.

The only change i would love to see is the `datapacks` folder to be yanked out of `config` and placed on `.minecraft\`/Game Directory folder root, to be paired with `resourcepack` and look more how vanilla should implement this feature themselves.

I know there is a couple of alternatives out there, but this one, being simple as that, is my favorite implementation.

**Comment by Commander07** [comment]
Hello, I have updated the mod for 1.19.3 and 1.19.4 I also implemented the tweak you suggested the new version should already be available on Modrinth and GitHub. CurseForge should be available soon.

**Comment by vico93** [comment]
Thank you so much!

**Comment by vico93** [comment]
Oh sorry to came back to pesk you, but unfortunately i pasted my datapacks on `<profile dir>\datapacks\` but none showed in the new world screen (only the build-in datapacks of both vanilla and fabric mods):

![2023-05-11_18 16 25](https://github.com/Commander07/data-loader/assets/3485505/bb5527ab-645b-48e1-a718-ad49fad1b9b1)

For reference, this is my `datapacks` folder contents:
![image](https://github.com/Commander07/data-loader/assets/3485505/8608db61-a0e4-40b0-b898-10bfe1de2064)

Also, for clarification, i'm using both `--workDir` to change the location of the whole `.minecraft` folder (to `C:\Jogos\Minecraft`) and also the installation have its dedicated game profile pointing to a subfolder of the custom folder i mentioned above (`C:\Jogos\Minecraft\profiles\vicocraft_1.12`). Would this be the source of the issue?

**Comment by vico93** [comment]
![image](https://github.com/Commander07/data-loader/assets/3485505/452f825a-cad8-4048-b23f-88b829a86786)
Yeah, seems like it just doesn't load on the new world menu. it works after creating the world.

But a option to tweak that screen on the client would be hugely necessary , specially to reorder the datapacks in case of those that requires to.

**Comment by Commander07** [comment]
My bad i forgot 1.19.4 added that, [this](https://github.com/Commander07/data-loader/releases/tag/1.1.1) version should allow you to modify the datapacks in the world creation screen.

**Comment by vico93** [comment]
> My bad i forgot 1.19.4 added that, [this](https://github.com/Commander07/data-loader/releases/tag/1.1.1) version should allow you to modify the datapacks in the world creation screen.

Oh, now it's working properly on client, thanks!

I also tested your mod on a dedicated server, and unfortunately seems like in there the datapacks still doesn't load.

With the same set of datapacks of the previous screenshots, i tried to boot my test server and realized only the internal datapacks were enabled:
![2023-05-11_19 30 56](https://github.com/Commander07/data-loader/assets/3485505/eb2881ac-5160-4b54-9932-6be92155ce84)

I tried specifically the datapacks present on `datapacks` folder on server.properties: `initial-enabled-packs=vanilla,update_1_20,bundle,fabric,tectonic\:tectonic-large-biomes,tectonic\:terratonic,arboria_v1.0.2.zip,vicocraft,vt_cauldron_concrete.zip,vt_confetti_creepers.zip,vt_crafting.zip,vt_unlock_all_recipes.zip` but all the non-internal packs are listed as missing during boot:
![image](https://github.com/Commander07/data-loader/assets/3485505/834c08e6-cb02-472e-8258-c1dc99b111dc)

**Comment by Commander07** [comment]
> > My bad i forgot 1.19.4 added that, [this](https://github.com/Commander07/data-loader/releases/tag/1.1.1) version should allow you to modify the datapacks in the world creation screen.
> 
> Oh, now it's working properly on client, thanks!
> 
> I also tested your mod on a dedicated server, and unfortunately seems like in there the datapacks still doesn't load.
> 
> With the same set of datapacks of the previous screenshots, i tried to boot my test server and realized only the internal datapacks were enabled: ![2023-05-11_19 30 56](https://user-images.githubusercontent.com/3485505/237826632-eb2881ac-5160-4b54-9932-6be92155ce84.png)
> 
> I tried specifically the datapacks present on `datapacks` folder on server.properties: `initial-enabled-packs=vanilla,update_1_20,bundle,fabric,tectonic\:tectonic-large-biomes,tectonic\:terratonic,arboria_v1.0.2.zip,vicocraft,vt_cauldron_concrete.zip,vt_confetti_creepers.zip,vt_crafting.zip,vt_unlock_all_recipes.zip` but all the non-internal packs are listed as missing during boot: ![image](https://user-images.githubusercontent.com/3485505/237826784-834c08e6-cb02-472e-8258-c1dc99b111dc.png)

This has been fixed in version 1.1.2 which can be found [here](https://modrinth.com/mod/dataloader/version/1.1.2+1.19.4).

**Comment by vico93** [comment]
Thank you so much!
