### ISSUE TITLE
About 1.20

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#3]
Sorry to be annoying again, but a build for 1.20-pre4 is feasible before the official release? I'm already developing a datapack for the future version of my modpack and i really miss your mod to facilitate things.

Also since it seems to be a huge update why not release at least one update for the pre versions, even to get acquainted with the internal changes of the new version?

Again, i apologize if the question sounds annoying, not my intention.

**Comment by vico93** [comment]
I tried my luck with https://github.com/Commander07/data-loader/pull/4. Let me know if i did something wrong on that PR. It's my first on a long time

**Comment by Commander07** [comment]
Closed by #4
