### ISSUE TITLE
[Feature Request] Tweak "Open Pack Folder" to open the datapacks folder

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#6]
Basically, on the _Select Data Packs_ menu, the Open Pack Folder button still create and open a temporary `mcworld-<random number>` folder on TEMP even with the current version of data-loader installed.

Since this feature of loading packs from a temporary folder isn't really relevant with data-loader around, i suggest the button behavior to be changed, to just open the `datapacks` folder instead of creating/opening a temporary only. Don't know how much difficult would be that to implement, but it would be just a small "aesthetical" change, no worry to implement that if you have interest too.

![image](https://github.com/Commander07/data-loader/assets/3485505/d26bd747-2fc8-4f68-b5d4-9f94b201b73c)

**Comment by Commander07** [comment]
Won't add because someone may still want to add a datapack only to a specific world.
