### ISSUE TITLE
[Suggestion] Configurable default datapack order for singleplayer

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#7]
I wonder if this mod could load a user-made load order of datapacks - consisting of a list of file/folder names (including internal packs like vanilla and fabric and the experimental bundle) in order to be mirrored everytime the player creates a world in singleplayer. For dedicated servers i feel the `initial-enabled-packs` directive on `server.properties` already serves for this purpose, but on singleplayer everytime we create a world we need to sort all the packs again, and if there is a huge number of packs to be loaded this would end up as a huge nuisiance.

**Comment by Commander07** [comment]
This has been added in [v1.1.4](https://modrinth.com/mod/dataloader/version/1.1.4+1.20.2-1.20.4)
