### ISSUE TITLE
v1.1.3 crashes with 1.20.2-pre2

### ISSUE THREAD

**Issue by vico93** [Commander07/data-loader#8]
Unfortunately, different from previous versions, this time Dataloader 1.1..3 crash when loaded on 1.20.2-pre2 (Loader 0.14.22, API 0.88.3) when entering the singleplayer create world screen.

[CRASH REPORT](https://gist.github.com/vico93/704b2fb330aea40db549ec07843b638a)

I bet the issue is related to the GUI assets changes Mojang is doing with that version, so maybe this is a quick fix, or not...

**Comment by Commander07** [comment]
1.20.2-pre2 support is not planned but 1.20.2 is now supported
